server {
    # listen
    listen 8080;
    listen 127.0.0.2:9090;


    client_max_body_size 1G;

    error_page 500 502 503 504 www/errors/50x.html;

    root www/;

    # root location
    location / {
        root www/static/
        methods GET;
        index index.html
        autoindex on;
    }

    location /post {
        methods POST;
        error_page 404 403 /errors/bad_request.html;
        upload_path www/uploads;
    }
}